<?php
	require_once("fpdf/fpdf.php");
    require_once("fpdf/pdf.php");
    require_once("dbcon-pdo.php");

	$pdf=new FPDF();
	
	
	function getTable($table, $exhibit)
	{
		try
		{
			$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
			$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			
			$state=$dbcon->prepare("SELECT ename FROM $exhibit WHERE tname=? AND layer='l2';");
			$state->execute(array($table));
			
			$row=$state->fetchAll();
			
			return $row;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
		
	}
	function getTableEval($table, $exhibit)
	{
		try
		{
			$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
			$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			
			$state=$dbcon->prepare("SELECT ename FROM $exhibit WHERE tname=? AND layer='l3';");
			$state->execute(array($table));
			
			$row=$state->fetchAll();
			
			return $row;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
	}
	function confirmEntry($user, $ex, $table, $eval)
    {
		try
		{
			$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
			$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			
			$state=$dbcon->prepare("SELECT evaluation FROM _documents_ WHERE uploaded_by=? AND master_exhibit=? AND from_which_table=? AND evaluation=?;");
			$state->execute(array($user, $ex, $table, $eval));
			$row=$state->fetchAll();
			return $row;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
        
    }
	function confirmEntry3($login, $pos, $dept, $l3_ev, $l2_table)
	{
		try
		{
			$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
			$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			$state=$dbcon->prepare("SELECT DISTINCT l3_evaluation FROM _documents3_ WHERE uploaded_by=? AND department=? AND position=? AND  l3_evaluation=? AND from_which_l2_eval=?;");
			$state->execute(array($login, $dept, $pos, $l3_ev, $l2_table));
			
			$row=$state->fetchAll();
			return $row;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
	}
	function dumpArray($a)
	{
		echo "<pre>";
			print_r($a);
		echo "</pre>";
	}
	
	$id=$_GET['id'];
    $exhibit=addslashes($_GET['exhibits']);
    $standards=$_GET['standards'];
	
	$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
	$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	
	$exhibit1=explode(" ", $_GET['exhibits']);
    $exhibit1=implode("", $exhibit1);
    $a=array();


    $tableName=array();
	
	
	#========================================
	try
	{
		// Get exhibit tables
		$state=$dbcon->prepare("SELECT tname FROM etable WHERE texhibit=?");
		$state->execute(array($exhibit));
		$tableName=$state->fetchAll();
	//	dumpArray($tableName);
		unset($state);
	}
	catch(PDOException $e)
	{
		echo $e->getMessage();
	}

	#========================================
	#==============PDF PROPER================
	#========================================

	$pdf->AddPage();
	$pdf->Image("images/faithlogo.png", 75, 6, 55);
	$pdf->SetFont('Helvetica','B',12);
	$pdf->SetY(30);
	$pdf->SetX(78);
	$pdf->Write(0, 'Quality Assurance Report');
	
	$pdf->SetX(10);

	$pdf->SetFont('Helvetica', '', 12);
	$pdf->SetLineWidth(1);
	
	$pdf->SetY(50);
	$pdf->SetX(10);
	$pdf->Write(0, "STANDARD TO COMPLY: ".$standards);
	$pdf->SetY(60);
	$pdf->SetX(10);
	$pdf->Write(0, "EXHIBIT NAME: ".$exhibit);
	
	$pdf->SetY(70);
	$pdf->SetX(210);
	$pdf->Write(0, "REPORT GENERATED BY USER: ".$_SESSION['login']." [".$_SESSION['position']."]");
	$pdf->SetX(15);
	
	for($i=0;$i<count($tableName);$i++)
	{
		$tArray=getTable($tableName[$i]['tname'], $exhibit1);
		for($j=0;$j<count($tArray); $j++)
		{
			$pdf->AddPage();
			$pdf->Image("images/faithlogo.png", 76, 6, 55);
			$pdf->SetFont('Helvetica','B',12);
			$pdf->SetY(35);
			$pdf->SetX(76);
			$pdf->Write(0, 'Quality Assurance Report');
			
			$pdf->SetX(10);

			$pdf->SetFont('Helvetica', '', 12);
			$pdf->SetLineWidth(1);
			
			$pdf->SetY(55);
			$pdf->SetX(30);
			$pdf->Write(0, "Table ".($i+1)." of ".count($tableName).": ".$tableName[$i]['tname']);

			$pdf->SetY(65);
			$pdf->SetX(30);
            
            $con=confirmEntry($_SESSION['login'], $exhibit1, $tableName[$i]['tname'], $tArray[$j]['ename']);
            
            // CONFIRM ENTRY FOR L2
            //=================================================
            if($con)
            {
                if($con[0]['evaluation']==$tArray[$j]['ename'])
                {
                    $pdf->SetY(65);
                    $pdf->SetX(30);
                    $pdf->Write(0, ($i+1).".".($j+1)." ".$tArray[$j]['ename']);
                }
                else
                {
            //        dumpArray($con);
                    $pdf->SetY(65);
                    $pdf->SetX(30);
                    $pdf->SetTextColor(250, 0, 0);
                    $pdf->Write(0, ($i+1).".".($j+1)." ".$tArray[$j]['ename']);
                }
                $pdf->SetTextColor(0, 0, 0);
            }
            else if(!$con)
            {
            //    dumpArray($con);
                $pdf->SetY(65);
                $pdf->SetX(30);
                $pdf->SetTextColor(250, 0, 0);
                $pdf->Write(0, ($i+1).".".($j+1)." ".$tArray[$j]['ename']);
                $pdf->SetTextColor(0, 0, 0);
            }
            
            
            //=================================================
            			
			$evalArray=getTableEval($tArray[$j]['ename'], $exhibit1);
            
            // function confirmEntry3($login, $pos, $dept, $l3_ev, $l2_table)

 			for($k=0;$k<count($evalArray);$k++)
			{
                $con3=confirmEntry3($_SESSION['login'], $_SESSION['position'], $_SESSION['department'], $evalArray[$k]['ename'], $tArray[$j]['ename']);
                if($con3)
                {
                    if($con3[0]['l3_evaluation']==$evalArray[$k]['ename'])
                    {
                        $pdf->SetY(75+($k*12));
                        $pdf->SetX(35);
                        $pdf->Write(0, ($i+1).".".($j+1).".".($k+1)." ".$evalArray[$k]['ename']);
                    }
                    else
                    {
                        $pdf->SetY(75+($k*12));
                        $pdf->SetX(35);
                        $pdf->SetTextColor(250, 0, 0);
                        $pdf->Write(0, ($i+1).".".($j+1).".".($k+1)." ".$evalArray[$k]['ename']);
                    }
                    $pdf->SetTextColor(0, 0, 0);
                }
                else if(!$con3)
                {
                    $pdf->SetY(75+($k*12));
                    $pdf->SetX(35);
                    $pdf->SetTextColor(250, 0, 0);
                    $pdf->Write(0, ($i+1).".".($j+1).".".($k+1)." ".$evalArray[$k]['ename']);
                }
                $pdf->SetTextColor(0, 0, 0);
			}
 			  
			
			/* 	if($con3)
				{
					for($l=0;$l<count($con3);$l++)
					{
						if($evalArray[$k]['ename']==$con3[$l]['l3_evaluation'])
						{
							$pdf->SetY(75+($m*12));
							$pdf->SetX(35);
							$pdf->SetTextColor(0, 0, 0);
							$pdf->Write(0, ($i+1).".".($j+1).".".($m+1)." ".$evalArray[$m]['ename']);
						}
						else
						{
							$pdf->SetY(75+($m*12));
							$pdf->SetX(35);
							$pdf->SetTextColor(140, 0, 0);
							$pdf->Write(0, ($i+1).".".($j+1).".".($m+1)." ".$evalArray[$m]['ename']);
						}
						$pdf->SetTextColor(0, 0, 0);
					}
				}
				else if(!$con3)
				{
					for($m=0;$m<count($departments);$m++)
					{
						$pdf->SetY(75+($k*12));
						$pdf->SetX(148+($m*20));
						$pdf->SetFont('Helvetica', 'B', 20);
						$pdf->SetTextColor(180, 0, 0);
						$pdf->Write(0, "-");
						$pdf->SetTextColor(0, 0, 0);
						$pdf->SetFont('Helvetica', '', 12);
					}
				} */
			/* $con=confirmEntry($exhibit, $tableName[$i]['tname'], $tArray[$j]['ename']);
				if($con)
				{
					for($l=0;$l<count($con);$l++)
					{
						for($m=0;$m<count($evalArray);$m++)
						{
							$pdf->SetY(75+($m*12));
							$pdf->SetX(35);
							$pdf->Write(0, ($i+1).".".($j+1).".".($m+1)." ".$evalArray[$m]['ename']);
						}
							if($departments[$m]==$con[$l]['department'])
							{
								
							}
							else
							{
								
							}
						
					}
				}
				else if(!$con)
				{

				} */
		}	
	}
	$pdf->Output();
?>