<?php
	require_once("fpdf/fpdf.php");
    require_once("fpdf/pdf.php");
	require_once("dbcon-pdo.php");

	$pdf=new FPDF("L", 'mm', 'legal'); // L for landscape, mm for millimeter, legal for legal
	
	$departments=array("CCIT", "COE", "COPS", "CIHM", "CBA", "CAS", "CON", "QA", "VPA", "HR");
	
	$id=$_GET['id'];
    $exhibit=addslashes($_GET['exhibits']);
    $standards=$_GET['standards'];

	
	$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
	$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	
	#========================================
	#============ FUNCTIONS =================
	#========================================
	function getTable($table, $exhibit)
	{
		try
		{
           
			$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
			$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			
			$state=$dbcon->prepare("SELECT ename FROM $exhibit WHERE tname=? AND layer='l2';");
			$state->execute(array($table));
			
			$row=$state->fetchAll();
			
			return $row;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
		
	}
	function getTableEval($table, $exhibit)
	{
		try
		{
         
            $dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
			$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			
			$state=$dbcon->prepare("SELECT ename FROM $exhibit WHERE tname=? AND layer='l3';");
			$state->execute(array($table));
			
			$row=$state->fetchAll();
			
			return $row;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
	}
	function confirmEntry($ex, $table, $eval)
    {
		try
		{
            
			$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
			$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			
			$state=$dbcon->prepare("SELECT DISTINCT department FROM _documents_ WHERE master_exhibit=? AND from_which_table=? AND evaluation=?;");
			$state->execute(array($ex, $table, $eval));
			$row=$state->fetchAll();
			return $row;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
        
    }
	function confirmEntry3($l3_ev, $l2_table)
	{
		try
		{
            
			$dbcon=new PDO('mysql:host='.$GLOBALS['host'].';dbname='.$GLOBALS['dbase'], $GLOBALS['lin'], $GLOBALS['pwd']);
			$dbcon->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
			$state=$dbcon->prepare("SELECT DISTINCT department FROM _documents3_ WHERE l3_evaluation=? AND from_which_l2_eval=?;");
			$state->execute(array($l3_ev, $l2_table));
			
			$row=$state->fetchAll();
			return $row;
		}
		catch(PDOException $e)
		{
			echo $e->getMessage();
		}
	}
    function fixRow($place)
    {
        return $place*11;
    }
	function dumpArray($a)
	{
		echo "<pre>";
			print_r($a);
		echo "</pre>";
	}
	
	#========================================
	#========================================
	
	$exhibit1=explode(" ", $_GET['exhibits']);
    $exhibit1=implode("", $exhibit1);
    $a=array();

	
	$tableName=array();
	
	
	#========================================
	try
	{
		// Get exhibit tables
		$state=$dbcon->prepare("SELECT tname FROM etable WHERE texhibit=?");
		$state->execute(array($exhibit));
		$tableName=$state->fetchAll();
	//	dumpArray($tableName);
		unset($state);
	}
	catch(PDOException $e)
	{
		echo $e->getMessage();
	}
	
    // Counter for rows
    $pageRowCount=0;
    $mul=1;

	#========================================
	#==============PDF PROPER================
	#========================================
	
	$pdf->AddPage();
	$dat_space=0;
	$pdf->Image("images/faithlogo.png", 150, 6, 55);
	$pdf->SetFont('Helvetica','B',12);
	$pdf->SetY(35);
	$pdf->SetX(152);
	$pdf->Write(0, 'Quality Assurance Report');
	

	$pdf->SetFont('Helvetica', '', 12);
	$pdf->SetLineWidth(1);
	
	$pdf->SetY(72);
	$pdf->SetX(10);
	$pdf->Write(0, "STANDARD TO COMPLY: ".$standards);
	$pdf->SetY(80);
	$pdf->SetX(10);
	$pdf->Write(0, "EXHIBIT NAME: ".$exhibit);
	$pdf->SetX(210);

	$pdf->SetY(100);
	$pdf->Write(0, "REPORT GENERATED BY USER: ".$_SESSION['login']." [".$_SESSION['position']."]");
	$pdf->SetX(15);
	
	for($i=0;$i<count($tableName);$i++)
	{

		$tArray=getTable($tableName[$i]['tname'], $exhibit1);
		for($j=0;$j<count($tArray); $j++)
		{
			$pdf->AddPage();
			$pdf->Image("images/faithlogo.png", 150, 6, 55);
			$pdf->SetFont('Helvetica','B',12);
			$pdf->SetY(35);
			$pdf->SetX(152);
			$pdf->Write(0, 'Quality Assurance Report');
			
			$pdf->SetX(10);

			$pdf->SetFont('Helvetica', '', 12);
			$pdf->SetLineWidth(1);
			
			$pdf->SetY(40);
			$pdf->SetX(10);
			$pdf->Write(0, "STANDARD TO COMPLY: ".$standards);
			$pdf->SetY(47);
			$pdf->SetX(10);
			$pdf->Write(0, "EXHIBIT NAME: ".$exhibit);
			
			$pdf->SetY(42);
			$pdf->SetX(210);
			$pdf->Write(0, "REPORT GENERATED BY USER: ".$_SESSION['login']." [".$_SESSION['position']."]");
			$pdf->SetX(15);

			$pdf->Line(12, 50, 344, 50);    // top
			$pdf->Line(344, 50, 344, 210);    // right
			$pdf->Line(12, 210, 344, 210);  // bottom
			$pdf->Line(12, 210, 12, 50);  // left

			$pdf->Line(12, 60, 344, 60);    // table row
			
			$pdf->SetY(55);
			$pdf->SetX(30);
			$pdf->Write(0, "Table ".($i+1)." of ".count($tableName).": ".$tableName[$i]['tname']);
			// Row for table name
			$departments=array("CCIT", "COE", "COPS", "CIHM", "CBA", "CAS", "CON", "QA", "VPA", "HR");
			//$pdf->Write(90, "Table ".($i+1)." of ".count($l2_array['evaluations'][$i]['subtables']).": ".$l2_array['l2tablenames'][$i]['tname']);
			// Write row for departments
			for($k=0;$k<count($departments);$k++)
			{
				$pdf->Line(141+($k*20), 50, 141+($k*20), 210);
				$pdf->SetY(55);
				$pdf->SetX(145+($k*20));
				$pdf->Write(0, $departments[$k]);
			}
			
			for($k=0;$k<12;$k++)
			{
				$pdf->Line(12, 70+($k*12), 344, 70+($k*12));
			}
			$pdf->SetY(65);
			$pdf->SetX(30);
			$pdf->Write(0, ($i+1).".".($j+1)." ".$tArray[$j]['ename']);
			$evalArray=getTableEval($tArray[$j]['ename'], $exhibit1);
            
            $con=confirmEntry($exhibit1, $tableName[$i]['tname'], $tArray[$j]['ename']);
            $confirmedDept=array();
            if($con)
            {
                for($l=0;$l<count($con);$l++)
                {
                    for($m=0;$m<count($departments);$m++)
                    {
                        if($departments[$m]==$con[$l]['department'])
                            $confirmedDept[]=$departments[$m];
                    }
                    
                }
                for($m=0;$m<count($departments);$m++)
                {
                    if(in_array($departments[$m], $confirmedDept))
                    {
                        $pdf->SetY(65);
                        $pdf->SetX(148+($m*20));
                        $pdf->SetFont('Helvetica', 'B', 20);
                        $pdf->SetTextColor(0, 100, 0);
                        $pdf->Write(0, "O");
                        $pdf->SetTextColor(0, 0, 0);
                        $pdf->SetFont('Helvetica', '', 12);
                    }
                    else
                    {
                       $pdf->SetY(65);
                       $pdf->SetX(148+($m*20));
                       $pdf->SetFont('Helvetica', 'B', 20);
                       $pdf->SetTextColor(180, 0, 0);
                       $pdf->Write(0, "-");
                       $pdf->SetTextColor(0, 0, 0);
                       $pdf->SetFont('Helvetica', '', 12);
                    }
                }
            }
            else if(!$con)
            {
                for($m=0;$m<count($departments);$m++)
                {
                    $pdf->SetY(65);
                    $pdf->SetX(148+($m*20));
                    $pdf->SetFont('Helvetica', 'B', 20);
                    $pdf->SetTextColor(180, 0, 0);
                    $pdf->Write(0, "-");
                    $pdf->SetTextColor(0, 0, 0);
                    $pdf->SetFont('Helvetica', '', 12);
                }
            }
//            echo count($evalArray);
            $pageRowCount=0;
            $mul=1;
			for($k=0;$k<count($evalArray);$k++)
			{
                $con3=confirmEntry3($evalArray[$k]['ename'], $tArray[$j]['ename']);
                if($pageRowCount%11==0 && $pageRowCount!=0)
                {
                    $pdf->AddPage();
                    
                    $pdf->Image("images/faithlogo.png", 150, 6, 55);
                    $pdf->SetFont('Helvetica','B',12);
                    $pdf->SetY(35);
                    $pdf->SetX(152);
                    $pdf->Write(0, 'Quality Assurance Report');

                    $pdf->SetX(10);

                    $pdf->SetFont('Helvetica', '', 12);
                    $pdf->SetLineWidth(1);

                    $pdf->SetY(40);
                    $pdf->SetX(10);
                    $pdf->Write(0, "STANDARD TO COMPLY: ".$standards);
                    $pdf->SetY(47);
                    $pdf->SetX(10);
                    $pdf->Write(0, "EXHIBIT NAME: ".$exhibit);

                    $pdf->SetY(42);
                    $pdf->SetX(210);
                    $pdf->Write(0, "REPORT GENERATED BY USER: ".$_SESSION['login']." [".$_SESSION['position']."]");
                    $pdf->SetX(15);

                    $pdf->Line(12, 50, 344, 50);    // top
                    $pdf->Line(344, 50, 344, 210);    // right
                    $pdf->Line(12, 210, 344, 210);  // bottom
                    $pdf->Line(12, 210, 12, 50);  // left

                    $pdf->Line(12, 60, 344, 60);    // table row

                    $pdf->SetY(55);
                    $pdf->SetX(30);
                    $pdf->Write(0, "Table ".($i+1)." of ".count($tableName).": ".$tableName[$i]['tname']);
                    // Row for table name

                    $departments=array("CCIT", "COE", "COPS", "CIHM", "CBA", "CAS", "CON", "QA", "VPA", "HR");
                    //$pdf->Write(90, "Table ".($i+1)." of ".count($l2_array['evaluations'][$i]['subtables']).": ".$l2_array['l2tablenames'][$i]['tname']);
                    // Write row for departments
                    for($l=0;$l<count($departments);$l++)
                    {
                        $pdf->Line(141+($l*20), 50, 141+($l*20), 210);
                        $pdf->SetY(55);
                        $pdf->SetX(145+($l*20));
                        $pdf->Write(0, $departments[$l]);
                    }

                    for($l=0;$l<12;$l++)
                    {
                        $pdf->Line(12, 70+($l*12), 344, 70+($l*12));
                    }

                    $pdf->SetY(65);
                    $pdf->SetX(30);
                    $pdf->Write(0, ($i+1).".".($j+1)." ".$tArray[$j]['ename']." (continued)");
                    $evalArray=getTableEval($tArray[$j]['ename'], $exhibit1);
                    
                    $con=confirmEntry($exhibit1, $tableName[$i]['tname'], $tArray[$j]['ename']);
                    $confirmedDept=array();
                    if($con)
                    {
                        for($l=0;$l<count($con);$l++)
                        {
                            for($m=0;$m<count($departments);$m++)
                            {
                                if($departments[$m]==$con[$l]['department'])
                                    $confirmedDept[]=$departments[$m];
                            }
                        }
                        for($m=0;$m<count($departments);$m++)
                        {
                            if(in_array($departments[$m], $confirmedDept))
                            {
                                $pdf->SetY(65);
                                $pdf->SetX(148+($m*20));
                                $pdf->SetFont('Helvetica', 'B', 20);
                                $pdf->SetTextColor(0, 100, 0);
                                $pdf->Write(0, "O");
                                $pdf->SetTextColor(0, 0, 0);
                                $pdf->SetFont('Helvetica', '', 12);
                            }
                            else
                            {
                                $pdf->SetY(65);
                                $pdf->SetX(148+($m*20));
                                $pdf->SetFont('Helvetica', 'B', 20);
                                $pdf->SetTextColor(180, 0, 0);
                                $pdf->Write(0, "-");
                                $pdf->SetTextColor(0, 0, 0);
                                $pdf->SetFont('Helvetica', '', 12);
                            }
                        }
                    }
                    else if(!$con)
                    {
                        for($m=0;$m<count($departments);$m++)
                        {
                            $pdf->SetY(65);
                            $pdf->SetX(148+($m*20));
                            $pdf->SetFont('Helvetica', 'B', 20);
                            $pdf->SetTextColor(180, 0, 0);
                            $pdf->Write(0, "-");
                            $pdf->SetTextColor(0, 0, 0);
                            $pdf->SetFont('Helvetica', '', 12);
                        }
                    }
                }
                

                $pdf->SetY(75+(($k%11)*12));
                $pdf->SetX(35);
                $pdf->Write(0, ($i+1).".".($j+1).".".($k+1)." ".$evalArray[$k]['ename']);
                $pageRowCount++;
                //echo $tArray[$j]['ename'];
                $confirmedDept3=array();
                if($con3)
                {
                    for($l=0;$l<count($con3);$l++)
                    {
                        for($m=0;$m<count($departments);$m++)
                        {
                            if($departments[$m]==$con3[$l]['department'])
                                $confirmedDept3[]=$departments[$m];
                        }
                    }
                    for($m=0;$m<count($departments);$m++)
                    {
                        if(in_array($departments[$m], $confirmedDept3))
                        {
                            $pdf->SetY(75+(($k%11)*12));
                            $pdf->SetX(148+($m*20));
                            $pdf->SetFont('Helvetica', 'B', 20);
                            $pdf->SetTextColor(0, 100, 0);
                            $pdf->Write(0, "O");
                            $pdf->SetTextColor(0, 0, 0);
                            $pdf->SetFont('Helvetica', '', 12);
                        }
                        else
                        {
                            $pdf->SetY(75+(($k%11)*12));
                            $pdf->SetX(148+($m*20));
                            $pdf->SetFont('Helvetica', 'B', 20);
                            $pdf->SetTextColor(180, 0, 0);
                            $pdf->Write(0, "-");
                            $pdf->SetTextColor(0, 0, 0);
                            $pdf->SetFont('Helvetica', '', 12);
                        }
                    }
                }
                else if(!$con3)
                {
                    for($m=0;$m<count($departments);$m++)
                    {
                        $pdf->SetY(75+(($k%11)*12));
                        $pdf->SetX(148+($m*20));
                        $pdf->SetFont('Helvetica', 'B', 20);
                        $pdf->SetTextColor(180, 0, 0);
                        $pdf->Write(0, "-");
                        $pdf->SetTextColor(0, 0, 0);
                        $pdf->SetFont('Helvetica', '', 12);
                    }
                }				
			}
		}
	}
	
	$pdf->Output();
	
	
?>	